//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class albaranes
    {
        public int clave { get; set; }
        public string NUMALB { get; set; }
        public System.DateTime FECHALB { get; set; }
        public string NUMPEDIDO { get; set; }
        public int NUMLINEAPED { get; set; }
        public string CUENTA { get; set; }
        public string FCOBRO { get; set; }
        public int NUMLINEA { get; set; }
        public string ARTI { get; set; }
        public string DESARTI { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> CANTI { get; set; }
        public Nullable<decimal> EUROS { get; set; }
        public Nullable<decimal> IVARTI { get; set; }
        public Nullable<decimal> DTOARTI { get; set; }
        public string ESTADO { get; set; }
        public string ESTADOLIN { get; set; }
        public string OBSERVACIONES { get; set; }
        public string FACTURADO { get; set; }
    }
}
