//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo_proveedor
    {
        public int id { get; set; }
        public int articulo_codigo { get; set; }
        public string proveedor_codigo { get; set; }
        public string descripcion_proveedor { get; set; }
        public Nullable<decimal> tarifa { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public string unidad { get; set; }
    
        public virtual articulo articulo { get; set; }
    }
}
