//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.articulo_proveedor = new HashSet<articulo_proveedor>();
        }
    
        public int codigo { get; set; }
        public string articulo1 { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> longitud { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<decimal> anchura { get; set; }
        public string tipo { get; set; }
        public string unidad_medida { get; set; }
        public string pais_origen { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<bool> es_reutilizable { get; set; }
        public Nullable<decimal> huella_carbono { get; set; }
        public Nullable<decimal> dto_base { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<bool> activo { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo_proveedor> articulo_proveedor { get; set; }
    }
}
