//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asientos
    {
        public string CONCEPTO { get; set; }
        public Nullable<decimal> ASIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_ASIENTO { get; set; }
        public string OBSERVACION { get; set; }
        public string CUENTA { get; set; }
        public string DH { get; set; }
        public Nullable<decimal> EUROS { get; set; }
        public decimal CLAVE { get; set; }
    }
}
