//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos
    {
        public string CUENTA { get; set; }
        public string NOMBRE_CUENTA { get; set; }
        public string NOMBRE_FISCAL { get; set; }
        public string DIRECCION { get; set; }
        public string CP { get; set; }
        public string POBLACION { get; set; }
        public string CIF { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
    }
}
