//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobros
    {
        public string FCOBRO { get; set; }
        public string NUMFAC { get; set; }
        public Nullable<System.DateTime> FECHA_VEN { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string CUENTA { get; set; }
        public Nullable<decimal> GASTOS { get; set; }
        public string BANCO { get; set; }
        public Nullable<System.DateTime> FECHA_LIB { get; set; }
        public Nullable<System.DateTime> FECH_FAC { get; set; }
        public string NUMEFEC { get; set; }
        public Nullable<System.DateTime> FESTADO { get; set; }
        public Nullable<System.DateTime> FRECEP { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<bool> EMITIDO { get; set; }
        public Nullable<bool> VENCIDO { get; set; }
        public Nullable<long> NPAGARE { get; set; }
        public string ESTADO { get; set; }
    }
}
