//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fpagcob
    {
        public string CODIGO { get; set; }
        public string FORMACOBPAG { get; set; }
        public string ACEPTO { get; set; }
        public string REMESACOBRO { get; set; }
        public string REMESAPAGO { get; set; }
        public int NUMCOBROS { get; set; }
        public int PRIMVENCI { get; set; }
        public int DIASVENCI { get; set; }
    }
}
