//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cortechecoEntities1 : DbContext
    {
        public cortechecoEntities1()
            : base("name=cortechecoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<albaranes> albaranes { get; set; }
        public virtual DbSet<albaranescom> albaranescom { get; set; }
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<articulo_proveedor> articulo_proveedor { get; set; }
        public virtual DbSet<asientos> asientos { get; set; }
        public virtual DbSet<bancos> bancos { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<cobros> cobros { get; set; }
        public virtual DbSet<cuentas> cuentas { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<facturascom> facturascom { get; set; }
        public virtual DbSet<fpagcob> fpagcob { get; set; }
        public virtual DbSet<ofertas> ofertas { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<pedidoscom> pedidoscom { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<tipos> tipos { get; set; }
        public virtual DbSet<unidades> unidades { get; set; }
        public virtual DbSet<compras_albaranes> compras_albaranes { get; set; }
        public virtual DbSet<compras_pedidos> compras_pedidos { get; set; }
        public virtual DbSet<compras_facturas> compras_facturas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
