//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexeron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public long CLAVE { get; set; }
        public string FPAGO { get; set; }
        public string NUMFAC { get; set; }
        public Nullable<System.DateTime> FECHA_VEN { get; set; }
        public decimal IMPORTE { get; set; }
        public string CUENTA { get; set; }
        public Nullable<System.DateTime> FECHA_LIB { get; set; }
        public Nullable<System.DateTime> FECH_FAC { get; set; }
        public string BANCO { get; set; }
        public string SFRA { get; set; }
        public string OBSERVACION { get; set; }
        public string EMITIDO { get; set; }
        public Nullable<bool> VENCIDO { get; set; }
    }
}
